server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update  #테이블 생성
    properties:
      .hibernate:
        show_sql: true  #sql 쿼리 확인
        format_sql: true # 가독성 좋게 포맷팅

    database-platform=org: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


